### ISSUE TITLE
StackTrace is not available if test fails on TestFixtureSetUp

### ISSUE THREAD

**Issue by Andrii-Cherepakha** [reportportal/agent-net-nunit2#3]
StackTrace is not available if test fails on TestFixtureSetUp

**Comment by nvborisenko** [comment]
@Andrey-Cherepakha, is it still actual for you. We don't support nunit2. Please take a look at nunit3, thx.

**Comment by Andrii-Cherepakha** [comment]
No actual any more since Nunit 3 is used
